# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/gcloud-plus', '-f', 'Dockerfile', '.']

# Simple sanity check: invoke the new gcloud container to confirm that it was
# built correctly.
- name: 'gcr.io/$PROJECT_ID/gcloud-plus'
  args: ['info']

# Invoke a command that requires auth, to check that it gets piped through
# correctly.
#- name: 'gcr.io/$PROJECT_ID/gcloud-plus'
#  args: ['source', 'repos', 'clone', 'default']

images:
- 'gcr.io/$PROJECT_ID/gcloud-plus'

timeout: 1200s
